### ISSUE TITLE
What is the Thermite Game

### ISSUE THREAD

**Issue by DavidAGullo** [qbcore-framework/qb-bitmining#5]
I get a Script error trying to use this.

SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export thermiteminigame in resource memorygame

**Comment by morwic** [comment]
you need to have the minigame on your server :)

**Comment by NupNipz** [comment]
> you need to have the minigame on your server :)

could you send a link to the needed minigame? i can`t find it anywhere.

**Comment by ihyajb** [comment]
@GhzGarage this can be closed because of the newest PR
